on: # build docker images
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Build and push docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: santi10/ciregistryocto
        tags: latest 
        registry: docker.io
        dockerfile: gdk5m/gdk5m_linux.Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
